"""Shopping demo — runs the multi-agent product-discovery pipeline end-to-end.

Mirrors run_investigation_demo.py but with the shopping_graph and a JOSEPHA-style
query: a Swiss-franc-priced consumer product comparison. Uses MOCK_TOOLS=true to
return curated fixtures from src/tools/_mock_data.py instead of hitting real
e-commerce / review-aggregator integrations.

Output: prints the final recommendation and writes it to examples/sample_shopping.md.
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path

# mocks must be active before tool modules cache the env
os.environ["MOCK_TOOLS"] = "true"

from src.graph.shopping_graph import run_shopping_session  # noqa: E402

DEMO_QUERY = (
    "I'm looking to buy wireless earbuds under CHF 200 — best balance of sound, "
    "active noise cancellation, and battery life for daily commuting in Zurich. "
    "Recommend the top pick with reasoning."
)

OUTPUT_PATH = Path(__file__).parent.parent / "examples" / "sample_shopping.md"


async def main() -> None:
    print("=" * 78)
    print("SHOPPING DEMO — multi-agent product discovery with Langfuse tracing")
    print("=" * 78)
    print(f"\nQuery:\n  {DEMO_QUERY}\n")
    print("Running graph (this may take 30-90 seconds)...\n")

    state = await run_shopping_session(DEMO_QUERY)

    print("─" * 78)
    print("AGENT SEQUENCE")
    print("─" * 78)
    for i, agent in enumerate(state.get("agent_sequence", []), 1):
        print(f"  {i:2d}. {agent}")

    findings_summary = {
        "product_findings": len(state.get("product_findings", [])),
        "review_findings": len(state.get("review_findings", [])),
        "price_findings": len(state.get("price_findings", [])),
    }
    print("\nFindings collected:")
    for k, v in findings_summary.items():
        print(f"  - {k}: {v}")

    recommendation = state.get("final_recommendation", "")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        f"# Sample Shopping Recommendation\n\n"
        f"_Generated by the multi-agent product-discovery pipeline (shopping extension "
        f"of the investigation system architecture)._\n\n"
        f"**Query:** {DEMO_QUERY}\n\n"
        f"**Session ID:** `{state['session_id']}`\n\n"
        f"**Agent sequence:** {' → '.join(state.get('agent_sequence', []))}\n\n"
        f"---\n\n{recommendation}\n"
    )
    print(f"\nRecommendation written to: {OUTPUT_PATH.relative_to(Path.cwd())}")
    print("\nCheck the Langfuse dashboard for the full trace.")


if __name__ == "__main__":
    asyncio.run(main())
