"""Investigation demo — runs the full multi-agent investigation pipeline end-to-end.

Activates `MOCK_TOOLS=true` so external retrieval tools (Azure AI Search, Bing)
return fixture data instead of hitting paid services. The agent code, supervisor
routing, evaluator, and Langfuse integration all run unchanged — only the two
outermost adapter functions are mocked.

Output: prints the final report and writes it to examples/sample_investigation.md.
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path

# mocks must be active before tool modules cache the env
os.environ["MOCK_TOOLS"] = "true"

from src.evaluation.evaluator import ReportEvaluator  # noqa: E402
from src.graph.investigation_graph import run_investigation  # noqa: E402

DEMO_QUERY = (
    "Investigate Tesla's financial risks following Q3 2024 earnings. "
    "Cover automotive margin trends, free cash flow quality, regulatory headwinds "
    "(NHTSA / FSD), and product execution risks (Cybertruck). Provide a structured "
    "investigation report with severity ratings and recommendations."
)

OUTPUT_PATH = Path(__file__).parent.parent / "examples" / "sample_investigation.md"


async def main() -> None:
    print("=" * 78)
    print("INVESTIGATION DEMO — multi-agent run with Langfuse tracing")
    print("=" * 78)
    print(f"\nQuery:\n  {DEMO_QUERY}\n")
    print("Running graph (this may take 30-90 seconds)...\n")

    state = await run_investigation(DEMO_QUERY)

    print("─" * 78)
    print("AGENT SEQUENCE")
    print("─" * 78)
    for i, agent in enumerate(state.get("agent_sequence", []), 1):
        print(f"  {i:2d}. {agent}")

    findings_summary = {
        "document_findings": len(state.get("document_findings", [])),
        "financial_findings": len(state.get("financial_findings", [])),
        "web_findings": len(state.get("web_findings", [])),
    }
    print("\nFindings collected:")
    for k, v in findings_summary.items():
        print(f"  - {k}: {v}")

    report = state.get("final_report", "")

    print("\n" + "─" * 78)
    print("EVALUATION")
    print("─" * 78)
    evaluator = ReportEvaluator()
    findings_dict = {
        "document_analyst": state.get("document_findings", []),
        "financial_analyst": state.get("financial_findings", []),
        "web_researcher": state.get("web_findings", []),
    }
    eval_result = evaluator.evaluate(report, findings_dict)
    print(f"  Overall:        {eval_result.overall_score:.3f}")
    print(f"  Hallucination:  {eval_result.hallucination_score:.3f}")
    print(f"  Citation:       {eval_result.citation_score:.3f}")
    print(f"  Completeness:   {eval_result.completeness_score:.3f}")
    print(f"  Coherence:      {eval_result.coherence_score:.3f}")
    print(f"  Passed:         {eval_result.passed}")
    if eval_result.issues:
        print(f"  Issues: {eval_result.issues}")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        f"# Sample Investigation Report\n\n"
        f"_Generated by the LangGraph multi-agent investigation system._\n\n"
        f"**Query:** {DEMO_QUERY}\n\n"
        f"**Investigation ID:** `{state['investigation_id']}`\n\n"
        f"**Agent sequence:** {' → '.join(state.get('agent_sequence', []))}\n\n"
        f"**Evaluation scores:** overall {eval_result.overall_score:.2f} · "
        f"hallucination {eval_result.hallucination_score:.2f} · "
        f"citation {eval_result.citation_score:.2f} · "
        f"coherence {eval_result.coherence_score:.2f}\n\n"
        f"---\n\n{report}\n"
    )
    print(f"\nReport written to: {OUTPUT_PATH.relative_to(Path.cwd())}")
    print("\nCheck the Langfuse dashboard for the full trace.")


if __name__ == "__main__":
    asyncio.run(main())
